project:
  type: website
  output-dir: docs

website:
  title: "Rannyele P. Ribeiro, PhD"
  site-url: https://rannypribeiro.github.io
  description: "This is Ranny Ribeiro's personal website."
  favicon: logo.jpg
  navbar:
    right:
      - text: News
        href: blog.qmd
      - text: Bio
        href: aboutme.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Resources
        href: resources.qmd
      - text: Outreach
        href: outreach.qmd
      - text: Sci-art
        href: sci-art.qmd
      - icon: github
        href: https://github.com/rannypribeiro
format:
  html:
    theme: flatly
    css: styles.css
    include-in-header: <meta name="google-site-verification" content="0O3BzS03eMxlsOZrglhcM_zT4lko2p2kGoR5dhwpGyY" />

editor: visual

