project:
  type: website
  output-dir: docs

website:
  title: "Ranny P. Ribeiro, PhD"
  site-url: https://rannypribeiro.github.io
  description: "This is Ranny Ribeiro's personal Blog."
  navbar:
    right:
      - text: Bio
        href: aboutme.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Resources
        href: resources.qmd
      - text: Outreach
        href: outreach.qmd
      - text: Sci-art
        href: sci-art.qmd
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/rannypribeiro
      - icon: twitter
        href: https://twitter.com/rannypribeiro
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

