---
title: Outreach
---

## WUPS Outreach

Ranny currently serves as the Outreach Director of the WashU Postdoc Society (WUPS). Under her leadership, the society launched two major initiatives: the Rapid Fire Round and the WUPS Podcast. These projects are the result of a highly motivated team working to showcase the incredible contributions that postdocs are making to the humanity and beyond.

### Rapid Fire Round

The WUPS Outreach Committee of WUPS started a series of interviews with postdocs to showcase their work and value. Many people are unaware of what it means to be a postdoc, and through these interviews, we aim to communicate this to a broader audience, even sharing it with our families. On a lighter note, when discussing this project, I was inspired by my grandparents, who still think I am a student. They're not entirely wrong, because being a scientist involves a lifelong journey of studying, but to produce knowledge. And knowledge is an invaluable product!

To access our interviews, please visit the [Rapid Fire Round](https://sites.wustl.edu/wupostdocsociety/who-are-we/rapid-fire-round-with-a-postdoc-2-2-2/).

### WUPS podcast

With goals similar to the Rapid Fire Round, the WUPS Outreach Committee has expanded to include a podcast. In this new format, we interview postdocs, faculty members, and other researchers to discuss science in both audio and video formats. Dr. Rishabh Bajpai hosts the podcast, with Ranny serving as the co-host. Check it out here: [WUPS podcast](https://open.spotify.com/episode/1Raf4dgjNCUqLYjIOeo9wT?si=659b74a575e0477d).
