---
title: Publications
---

## **Pre-prints**

**Ribeiro, R.P.**, Null, R.W., Ozpolat, D.B. Sex-biased gene expression precedes sexual dimorphism in the agonadal annelid *Platynereis dumerilii*. bioRxiv 2024.06.12.598746; [Link](https://doi.org/10.1101/2024.06.12.598746)

## **Research articles**

17. Spieß, V.\**,* **Ribeiro, R.P.\***, Helm, C., Aguado, M.T. (2024) From two segments and beyond: investigating the onset of regeneration in *Syllis malaquini* (Syllidae, Annelida). Evolution & Development, e12492. [Link](https://doi.org/10.1111/ede.12492) \*Authors with equal contributions.

18. **Ribeiro, R.P.**, Freitas, R., Zanol, J., Paiva, P.C., Fukuda, M.V., Guilment, T., Ruta, C. (2023) Genetic diversity of polychaete annelids from the Saint Peter and Saint Paul Archipelago, Equatorial Atlantic, with description of a new species. Regional Studies in Marine Science,68, 103243. [Link](https://doi.org/10.1016/j.rsma.2023.103243).

<!-- -->

15. Ruta, C., Mundin, D., Freitas, R., **Ribeiro, R.P.** (2023) New species and record of *Dodecaceria* (Annelida: Cirratulidae) from the only atoll in the South Atlantic Ocean, the Biological Reserve of Rocas Atoll, Brazil. PLOS ONE, 18(10): e0293087. [Link](https://doi.org/10.1371/journal.pone.029308)

<!-- -->

14. Freitas, R., **Ribeiro, R.P.**, Ruta, C. (2022) *Kirkegaardia* Blake, 2016 (Annelida: Cirratulidae) from Southeastern Brazil with description of nine new species. PLOS ONE, 17(5):e0265336. [Link](https://doi.org/10.1371/journal.pone.0265336)

<!-- -->

13. Paula, M.S., Freitas, R., Barbosa, C.A.M., **Ribeiro, R.P.**, Ruta, C. (2022) Bycatch of Asteroidea from shrimp trawl fishery in the southwestern Atlantic Ocean – Brazil. Papeis Avulsos de Zoologia. 62, e202262007. [Link](https://doi.org/10.11606/1807-0205/2022.62.007)

<!-- -->

12. Aguado, M. T., Ponz-Segrelles, G., Glasby, C.J., **Ribeiro, R.P.**, Nakamura, M., Oguchi, K., Omori, A., Kohtsuka, H., Fisher, C., Ise, Y., Jimi, N., Miura, T. (2022). *Ramisyllis kingghidorahi*, a new branching annelid from Japan. Organisms Diversity and Evolution, 22, 377–405. [Link](https://doi.org/10.1007/s13127-021-00538-4)

<!-- -->

11. **Ribeiro, R.P.**, Aguado, M.T. (2021) Effects of GSK3β inhibition in the regeneration of *Syllis malaquini* (Syllidae, Annelida). Development, Genes and Evolution, 231, 141–146. [Link](https://doi.org/10.1007/s00427-021-00681-0)

<!-- -->

10. **Ribeiro, R.P.**, Egger, B., Ponz-Segrelles, G., Aguado, M.T. (2021) Cellular proliferation dynamics during regeneration in *Syllis malaquini* (Syllidae, Annelida). Frontiers in Zoology, 18(1):1-16. [Link](https://doi.org/10.1186/s12983-021-00396-y)

<!-- -->

9.  Ponz-Segrelles, G., Glaby, C.J., Helm, C., Beckers, P.; Hammel, J.U., **Ribeiro, R.P.**, Aguado, M.T. (2021). Integrative anatomical study of the branched annelid *Ramisyllis multicaudata* (Annelida, Syllidae). Journal of Morphology, 282(6): 900-916. [Link](https://doi.org/10.1002/jmor.21356)

<!-- -->

8.  Ponz-Segrelles, G., **Ribeiro, R.P.**, Bleidorn, C., Aguado, M.T. (2020) Sex-specific gene expression differences in reproducing *Syllis prolifera* and *Nudisyllis pulligera* (Annelida, Syllidae). Marine Genomics, 54: 100772. [Link](https://doi.org/10.1016/j.margen.2020.100772)

<!-- -->

7.  **Ribeiro, R.P.**, Ponz-Segrelles, G., Helm, C., Egger, B., Aguado, M.T. (2020) A new species of *Syllis* Grube, 1850 including transcriptomic data and an updated phylogeny of Syllinae (Annelida: Syllidae). Marine Biodiversity, 50:31. [Link](#0)

<!-- -->

6.  **Ribeiro, R.P.**, Cruz, A.B., Freitas, R., Zanol, J., Glasby, C.J., Ruta, C. (2020) Pilargidae (Annelida: Phyllodocida) from coastal and deep waters of the Southwestern Atlantic, with descriptions of two new species. Zootaxa, 4878: 056–076. [Link](#0)

<!-- -->

5.  **Ribeiro, R.P.**, Ponz-Segrelles, G., Bleidorn, C., Aguado, M.T. (2019) Comparative transcriptomics in Syllidae (Annelida) indicates that posterior regeneration and regular growth are comparable, while anterior regeneration is a distinct process. BMC Genomics, 20:855. [Link](https://doi.org/10.1186/s12864-019-6223-y)

<!-- -->

4.  **Ribeiro, R.P.**, Alves, P.R., Almeida, Z.S., Ruta, C. (2018) A new species of *Paraonis* and an annotated checklist of polychaetes from mangroves of the Brazilian Amazon Coast (Annelida, Paraonidae). Zookeys, 740:1-34. [Link](#0)

<!-- -->

3.  Sousa, L.K.S., Cutrim, A.S.T., **Ribeiro, R.P.**, Oliveira, V.M., Almeida, Z.S. (2018) Marine quality assessment of amazon mangroves using benthic and diversity indices based on polychaete fauna. Boletim do Laboratório de Hidrobiologia, 28: 11-22.[Link](http://www.periodicoseletronicos.ufma.br/index.php/blabohidro/article/view/5554)

<!-- -->

2.  Cutrim, A.S.T., Sousa, L.K.S, **Ribeiro, R.P.**, Oliveira, V.M., Almeida, Z.S. (2018) Structure of a polychaete community in a mangrove in the northern coast of Brazil. Acta Biológica Colombiana, 23: 286-294. [Link](https://doi.org/10.15446/abc.v23n3.67245)

<!-- -->

1.  Rodrigues, C.A.L., **Ribeiro, R.P**.\*, Santos, N.B., Almeida, Z.S. (2016) Patterns of mollusc distribution in mangroves from the São Marcos Bay, coast of Maranhão State, Brazil. Acta Amazonica, 46: 391-400. \*RPR as corresponding author. [Link](http://dx.doi.org/10.1590/1809-4392201600493)

## **Reviews and book chapters**

4.  Ponz-Segrelles, G., **Ribeiro, R.P.**, Aguado, M.T. (2021) Monsters reveal patterns: annelids and their implications for the study of development and evolution. Biological Reviews, 97, 896–922. Review. [Link](https://doi.org/10.1111/brv.12826)

<!-- -->

3.  **Ribeiro, R.P.**, Bleidorn, C., Aguado, M.T. (2018) Regeneration mechanisms in Syllidae (Annelida). Regeneration, 5: 26-42. Review. [Link](https://doi.org/10.1002/reg2.98)

<!-- -->

2.  **Ribeiro, R.P.**, Almeida, Z.S. (2014) Polychaete annelids from the State of Maranhão, Brazil: history of knowledge. Bioikos, 28: 45-55. Review. \[in Portuguese\] [Link](https://periodicos.puc-campinas.edu.br/bioikos/article/view/2523)

<!-- -->

1.  **Ribeiro, R.P.**, Almeida, Z.S. (2013) Polychaeta. In: Nunes, J.L.S.; Medonça, M.A. (Eds.). Marine biodiversity of São Luís Island. São Luís: EDUFMA, 2013, p. 79-94. Book chapter \[in Portuguese\]

## **Publications in teaching**

4.  **Ribeiro, R.P.**, Hernández-González. (2021) Gamizoo: providing a courseware for practical classes of Zoology. Revista Docência do Ensino Superior, 11: 1-20, 2021. Research article. \[in Spanish\] [Link](https://doi.org/10.35699/2237-5864.2021.34334)

<!-- -->

3.  Marques, N.N.C.F., **Ribeiro, R.P.** (2016) An analysis of the contents of Biotechnology in the tests of the National High School Exam (ENEM). Pesquisa em Foco (UEMA), 21: 104-117, Research article. \[in Portuguese\][Link](https://ppg.revistas.uema.br/index.php/PESQUISA_EM_FOCO/article/view/1222)

<!-- -->

2.  **Ribeiro, R.P.** (2017) Training Biology teachers: supervised internship experiences. 1. ed. Rio de Janeiro: Câmara Brasileira de Jovens escritores, 66p. Book \[in Portuguese\]

<!-- -->

1.  Silva, J.R.S., Sousa, D.B.P., Cavalcanti, L.F., **Ribeiro, R.P.** (2016) Voices of (in) teaching: dialogue on pedagogical practices in Biological Sciences. In: Maria Cristina da Rosa Fonseca da Silva; Vera Márcia Marques Santos. (Eds.) Teacher training and public policies: scenarios and challenges. Florianópolis: Letras Contemporâneas, p. 212-230. Book chapter \[in Portuguese\]

## **Theses**

3.  **Ribeiro, R. P.** (2021). Regeneration in Syllidae (Annelida): morphological, cellular and genetic background. Autonomous University of Madrid). Doctoral dissertation. [Link](https://dialnet.unirioja.es/servlet/tesis?codigo=294960)

<!-- -->

2.  **Ribeiro, R. P.** (2015) Morphological and molecular diversity of polychaetes from Saint Peter and Saint Paul Archipelago. Federal University of Rio de Janeiro. Master’s dissertation. \[in Portuguese\]

<!-- -->

1.  **Ribeiro, R. P.** (2013) Characterization of the polychaete fauna in mangroves from two areas of the São Marcos Bay, Maranhão. State University of Maranhão. Bachelor’s thesis. \[in Portuguese\]
