---
title: Research
---

## **Regeneration and reproduction**

![Ranny studies regeneration and reproduction in marine segmented worms, also known as annelids. During her PhD, she investigated the relationship between regeneration and reproduction under an evolutionary perspective. Using diverse tools such as RNA sequencing, bioinformatics, and immunohistochemistry, she characterized cellular proliferation and the transcriptomic profile of anterior and posterior body regeneration in a specific group of annelids called syllids. Currently, her postdoctoral research is focused on understanding how these organisms regenerate there germ cells, and the dynamics of germ cell differentiation. Annelids stand out from other highly regenerative organisms like planarians and cnidarians due to the absence of specialized stem cells dedicated to regeneration. This absence raises an intriguing question: how do they achieve remarkable regenerative feats without relying on specific cell types? Unraveling this mystery holds the potential to manipulate regenerative processes in various cell types, including those found in vertebrates.](dramasyllis.jpg){height="348" fig-align="left"}

## **Annelid diversity and evolution**

![Ranny has devoted many years to studying the diversity of annelids Embarking on her scientific journey by collecting specimens from the mangroves of her hometown, São Luís (MA), Brazil, her initial venture into science involved taxonomical description of new species. Having overseen two projects for Bachelors and a Masters degree, and through collaborative research set alongside, she has described 15 annelid species. Furthermore, her expertise in taxonomy has facilitated her contributions to ecology, particularly in evaluating environmental health within both impacted and preserved marine ecosystems.](images/annelid.jpg){height="348px" fig-align="left"}
