---
title: Resources
---

## Teaching

### Course development

I like to employ different strategies for teaching. Recently, I took advantage of the flipped classroom concept and I developed some course material based on gamification. I think it is an effective approach for teaching and learning. I have crafted some resources for classes of Embryology, Zoology, English in three languages (Portuguese, Spanish and English). I used the platform [Genially](https://genial.ly/) to build these games. I absolutely recommend it. Also, I published a article about my experience using some the series "Gamizoo" during lab course of Zoology.

-   [Find the pairs](https://view.genial.ly/64a08c488441880018d2c10b/interactive-content-find-the-pairs-platynereis-germline). Embryology Course. \[English\]

-   [Gamizoo Bivalvos](https://view.genial.ly/607a93765a25e70d38bea411/interactive-content-gamizoo-bivalvos). Zoology course. \[Spanish\]

-   [Gamizoo Insectos](%7Bhttps://create.kahoot.it/share/gamizoo-insectos/8b3a338b-d3f6-43a9-ae6c-28a58355c091). Zoology course. \[Spanish\]

-   [Hobbying](https://view.genial.ly/5f8eb582c1228c0d8bb8de0c/game-hobbying). English course. \[Portuguese\]

-   [Gamizoo Aves de Navaseca](https://view.genial.ly/5f7af1efff5a000cf0bdde9f/game-aves-de-navaseca). Zoology course.\[Spanish\]

-   [Gamizoo Aves](https://view.genial.ly/5f7de4dd1b2b330d2efa20b4/game-identificacion-de-aves). Zoology course. \[Spanish\]

## Bioinformatics and coding resources

Helpful resources I utilize in Bioinformatics are accessible through my [GitHub account](https://github.com/rannypribeiro).

I created this website using [Quarto](https://quarto.org/), which is straightforward to manage even if you are not familiar with RStudio and R coding. The theme used is flatly.


